// auth
export const AUTH_START_LOADING = "AUTH_START_LOADING";
export const AUTH_STOP_LOADING = "AUTH_STOP_LOADING";
export const AUTH_SET_SUCCESS = "AUTH_SET_SUCCESS";
export const AUTH_CLEAR_SUCCESS = "AUTH_CLEAR_SUCCESS";
export const AUTH_SET_ERROR = "AUTH_SET_ERROR";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";


// compete
export const COMPETE_START_LOADING = "COMPETE_START_LOADING";
export const COMPETE_STOP_LOADING = "COMPETE_STOP_LOADING";
export const COMPETE_SET_SUCCESS = "COMPETE_SET_SUCCESS";
export const COMPETE_CLEAR_SUCCESS = "COMPETE_CLEAR_SUCCESS";
export const COMPETE_SET_ERROR = "COMPETE_SET_ERROR";
export const COMPETE_CLEAR_ERROR = "COMPETE_CLEAR_ERROR";
export const SET_READY = "SET_READY";
export const CLEAR_READY = "CLEAR_READY";
export const NOTIFY_NEW_ACTIVE_USERS = "NOTIFY_NEW_ACTIVE_USERS";
export const NEW_NOTIFICATION = "NEW_NOTIFICATION"; 
export const SET_NOTIFICATION_PUSHED = "SET_NOTIFICATION_PUSHED";
export const CLEAR_NOTIFICATION_PUSHED = "CLEAR_NOTIFICATION_PUSHED";
